import dayjs from 'dayjs/esm';

import { IPmEtablissement, NewPmEtablissement } from './pm-etablissement.model';

export const sampleWithRequiredData: IPmEtablissement = {
  id: 24935,
  idEtablissementRPG: 'inasmuch',
  codePartenaireDistributeur: 'gee excepting brochure',
  numeroSiretSiege: 'allegation um er',
  codeEtat: 'all hurtful',
  libelleEtat: 'shrilly gee amidst',
  codeCategoriePersonne: 'boring beneath cutlet',
  libelleCategoriePersonne: 'gee aw',
  codeType: 'meh',
  dateCreationJuridique: dayjs('2025-07-24'),
  dateEtat: dayjs('2025-07-24'),
  dateFermetureJuridique: dayjs('2025-07-24'),
  codeIDCC: 'absolve ha',
  codeTrancheEffectif: 'joyfully',
  libelleTrancheEffectif: 'seldom diligently',
  dateCessationActivite: dayjs('2025-07-24'),
  dateEffectifOfficiel: dayjs('2025-07-25'),
  effectifOfficiel: 'fussy',
  codeMotifCessationActivite: 'probate rout essential',
  siret: 'indeed draft assail',
  codeTypeEtablissement: 'lovable',
  libelleEnseigne: 'underneath',
  codeNIC: 'ack',
};

export const sampleWithPartialData: IPmEtablissement = {
  id: 30177,
  idEtablissementRPG: 'deliberately',
  codePartenaireDistributeur: 'snoop depute while',
  numeroSiretSiege: 'plus asset',
  codeEtat: 'vivaciously for howl',
  libelleEtat: 'when why',
  codeCategoriePersonne: 'phew',
  libelleCategoriePersonne: 'over uh-huh',
  codeType: 'rise rejoin',
  dateCreationJuridique: dayjs('2025-07-24'),
  dateEtat: dayjs('2025-07-24'),
  dateFermetureJuridique: dayjs('2025-07-24'),
  codeIDCC: 'wherever',
  codeTrancheEffectif: 'hmph drat deceivingly',
  libelleTrancheEffectif: 'hard-to-find',
  dateCessationActivite: dayjs('2025-07-25'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'hence fatally jubilantly',
  codeMotifCessationActivite: 'ha',
  siret: 'wherever aha',
  codeTypeEtablissement: 'pity for',
  libelleEnseigne: 'account mmm garrote',
  codeNIC: 'yogurt',
  identifiantAI: 'ha stool drat',
  checked: true,
};

export const sampleWithFullData: IPmEtablissement = {
  id: 22674,
  idEtablissementRPG: 'if yippee',
  codePartenaireDistributeur: 'pry task instead',
  numeroSiretSiege: 'good-natured ironclad',
  codeEtat: 'offset ugh fooey',
  libelleEtat: 'crackle wrongly',
  codeCategoriePersonne: 'for',
  libelleCategoriePersonne: 'tight marksman failing',
  codeType: 'er dress onto',
  dateCreationJuridique: dayjs('2025-07-25'),
  dateEtat: dayjs('2025-07-25'),
  dateFermetureJuridique: dayjs('2025-07-25'),
  codeIDCC: 'convoke follower',
  codeTrancheEffectif: 'hence yum once',
  libelleTrancheEffectif: 'hmph decide',
  dateCessationActivite: dayjs('2025-07-24'),
  dateEffectifOfficiel: dayjs('2025-07-25'),
  effectifOfficiel: 'velocity',
  codeMotifCessationActivite: 'consign',
  siret: 'terribly',
  codeTypeEtablissement: 'lazily',
  libelleEnseigne: 'throughout blowgun',
  codeNIC: 'before whoa',
  identifiantAI: 'pish anenst',
  checked: false,
};

export const sampleWithNewData: NewPmEtablissement = {
  idEtablissementRPG: 'illiterate as',
  codePartenaireDistributeur: 'apropos',
  numeroSiretSiege: 'as',
  codeEtat: 'so yet',
  libelleEtat: 'beneath unexpectedly earnest',
  codeCategoriePersonne: 'handsome carpool kookily',
  libelleCategoriePersonne: 'augment calmly',
  codeType: 'sprinkles black-and-white',
  dateCreationJuridique: dayjs('2025-07-24'),
  dateEtat: dayjs('2025-07-24'),
  dateFermetureJuridique: dayjs('2025-07-25'),
  codeIDCC: 'excitedly',
  codeTrancheEffectif: 'eek that',
  libelleTrancheEffectif: 'deselect glisten',
  dateCessationActivite: dayjs('2025-07-25'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'sugary whenever in-joke',
  codeMotifCessationActivite: 'likewise shocked',
  siret: 'sans ack characterization',
  codeTypeEtablissement: 'until polished rarely',
  libelleEnseigne: 'worth restructure corner',
  codeNIC: 'expatiate mantua nervously',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
