import dayjs from 'dayjs/esm';

import { IPmEntreprise, NewPmEntreprise } from './pm-entreprise.model';

export const sampleWithRequiredData: IPmEntreprise = {
  id: 29267,
  idEntrepriseRPG: 'yippee',
  codePartenaireDistributeur: 'glittering while',
  numeroSiretSiege: 'clearly hmph technician',
  codeEtat: 'duh potable',
  libelleEtat: 'ruddy',
  codeCategoriePersonne: 'mockingly appropriate suddenly',
  libelleCategoriePersonne: 'huff',
  codeType: 'unique pish',
  dateCreationJuridique: dayjs('2025-07-24'),
  dateEtat: dayjs('2025-07-24'),
  dateFermetureJuridique: dayjs('2025-07-25'),
  codeTrancheEffectif: 'gadzooks although muscat',
  libelleTrancheEffectif: 'trash plain',
  dateCessationActivite: dayjs('2025-07-24'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'who although',
  codeMotifCessationActivite: 'of uh-huh comestible',
  siren: 'outfox',
  codeFormeJuridique: 'um woot consequently',
  raisonSociale: 'phooey parade',
  codeCategorieJuridique: 'chow nor exacerbate',
  codeIDCC: 'indeed toward',
  codeAPE: 'advanced zowie',
};

export const sampleWithPartialData: IPmEntreprise = {
  id: 23639,
  idEntrepriseRPG: 'worthy',
  codePartenaireDistributeur: 'where softly immaculate',
  numeroSiretSiege: 'gladly nutritious',
  codeEtat: 'declaration shyly pine',
  libelleEtat: 'near aside zowie',
  codeCategoriePersonne: 'vaguely pfft sympathetically',
  libelleCategoriePersonne: 'amidst bitterly um',
  codeType: 'anenst um furiously',
  dateCreationJuridique: dayjs('2025-07-25'),
  dateEtat: dayjs('2025-07-25'),
  dateFermetureJuridique: dayjs('2025-07-24'),
  codeTrancheEffectif: 'shameless',
  libelleTrancheEffectif: 'maestro although',
  dateCessationActivite: dayjs('2025-07-24'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'heavenly into oh',
  codeMotifCessationActivite: 'during mooch',
  siren: 'ack',
  codeFormeJuridique: 'than furthermore',
  raisonSociale: 'on coal giving',
  codeCategorieJuridique: 'supposing zowie yum',
  codeIDCC: 'advanced',
  codeAPE: 'slushy',
  checked: false,
};

export const sampleWithFullData: IPmEntreprise = {
  id: 9584,
  idEntrepriseRPG: 'chasuble pilot shrill',
  codePartenaireDistributeur: 'bog',
  numeroSiretSiege: 'dally',
  codeEtat: 'satirise ah swiftly',
  libelleEtat: 'yowza fooey brown',
  codeCategoriePersonne: 'evince',
  libelleCategoriePersonne: 'positively',
  codeType: 'measly gosh softly',
  dateCreationJuridique: dayjs('2025-07-25'),
  dateEtat: dayjs('2025-07-24'),
  dateFermetureJuridique: dayjs('2025-07-25'),
  codeTrancheEffectif: 'since',
  libelleTrancheEffectif: 'publication major',
  dateCessationActivite: dayjs('2025-07-24'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'unit',
  codeMotifCessationActivite: 'consequently flood huzzah',
  siren: 'consequently',
  codeFormeJuridique: 'behind',
  raisonSociale: 'silver',
  codeCategorieJuridique: 'longboat gown hunger',
  codeIDCC: 'impact barring since',
  codeAPE: 'at uncork',
  identifiantAI: 'mockingly puff',
  checked: false,
};

export const sampleWithNewData: NewPmEntreprise = {
  idEntrepriseRPG: 'playfully',
  codePartenaireDistributeur: 'whoa whimsical expostulate',
  numeroSiretSiege: 'and unwelcome',
  codeEtat: 'summarise',
  libelleEtat: 'whenever finally',
  codeCategoriePersonne: 'inasmuch statement metabolise',
  libelleCategoriePersonne: 'aftermath gadzooks',
  codeType: 'well-to-do ugh ew',
  dateCreationJuridique: dayjs('2025-07-25'),
  dateEtat: dayjs('2025-07-25'),
  dateFermetureJuridique: dayjs('2025-07-24'),
  codeTrancheEffectif: 'rough elementary an',
  libelleTrancheEffectif: 'boastfully',
  dateCessationActivite: dayjs('2025-07-25'),
  dateEffectifOfficiel: dayjs('2025-07-24'),
  effectifOfficiel: 'hungrily',
  codeMotifCessationActivite: 'rectangular regarding',
  siren: 'forenenst fraudster um',
  codeFormeJuridique: 'puritan',
  raisonSociale: 'joyous mash',
  codeCategorieJuridique: 'yet',
  codeIDCC: 'madly until mediocre',
  codeAPE: 'maestro',
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
